config/test.exs
lib/railway_ipc/application.ex
lib/railway_ipc/connection.ex
lib/railway_ipc/consumer.ex
lib/railway_ipc/payload_behaviour.ex
lib/railway_ipc/publisher.ex
lib/railway_ipc/rabbit_mq/payload.ex
lib/railway_ipc/rabbit_mq/rabbit_mq_adapter.ex
lib/railway_ipc/stream_behaviour.ex
lib/railway_ipc/supervisor.ex
test/railway_ipc/connection_test.exs
test/railway_ipc/consumer_test.exs
test/railway_ipc/rabbit_mq/payload_test.exs
test/support/ipc/messages/create_batch.ex
test/support/mocks.ex

Make a channel per consumer per the Rabbit Docs, for better multiplexing. This also allows the calling app start the rabbit connection allowing for a "let it fail" strategy. Consumers are started under a separate supervisor to allow for individual consumer failure not restarting all other children. However if a catastrophic failure does happen to all consumers, it will restart the supervisor, which will restart the connection.

Channel per consumer

---

mix.exs

ran into the following error while publishing: 
`Publishing failed
inserted_at: can only modify a release up to one hour after creation`
Increased the version to account for that problem

bump version of package

---

mix.exs

Latest release does not include `priv/` dir in the release path. This is where migration templates live so new apps including Railway will fail to successfully execute the railway "generate migrations" mix task. Missed this cuz I generated migrations in Course Conductor using the local version of Railway before upgrading and shipping.

add priv dir to release path; bump version

---

.gitignore
README.md
lib/mix/support/migration_helper.ex
lib/mix/support/system_command_helper.ex
lib/mix/tasks/generate_alter_table_migrations.ex
lib/mix/tasks/generate_migrations.ex
lib/mix/tasks/generate_remove_exchange_constraint_migration.ex
lib/mix/tasks/update_protobufs.ex
mix.exs

Issues:
- On our current version, the generate command appears to work fine even if system commands fail
- Current version assumes the location of migrations, but migrations may be in a different place in the case of an umbrella app
Fix:
- Raise if system command fails
- Allow for the ability to pass in a location for migrations

Fix migration gen

---

CHANGELOG.md
lib/railway_ipc/consumed_message.ex
lib/railway_ipc/message_consumption.ex
test/railway_ipc/consumed_message_test.exs
test/railway_ipc/message_consumption_test.exs
test/railway_ipc/rabbit_mq/rabbit_mq_adapter_test.exs

- Locks message inside a transaction so this process holds the message until transaction is complete

Fix message locking

---

lib/railway_ipc/consumer_group/consumer_monitor.ex
lib/railway_ipc/consumer_group/consumer_supervisor.ex
lib/railway_ipc/consumer_group/supervisor.ex
test/railway_ipc/consumer_group/supervisor_test.exs

Failure is hard. This PR introduces a way to group consumers you _want_ to fail together.
To Group a set of consumers together You would add this to your supervision tree
```elixir
children = [
#... more things
RailwayIpc.ConsumerGroup.Supervisor.setup_group(children:[Consumer1, Consumer2],
name: :unique_name_for_this_consumer_group)
```
This will make it so that ANY of these consumers crashing, brings down ONLY other consumers in this consumer group.
There are consumers in our system where failure could lead to either inconsistent data being sent to 3rd party systems or failures in different consumers "at a distance". A failure to integrate a new Campus into our DB may not break ALL new Cohorts, but it will as soon as someone tries to add Cohort for that Campus. 
Other times, failures …

Add Consumer Group abstraction

---

lib/railway_ipc/consumer_pool.ex
lib/railway_ipc/publisher_pool.ex
lib/railway_ipc/rabbit_mq/rabbit_mq_adapter.ex
lib/railway_ipc/rpc_pool.ex

ExRabbitPool expects the connection credentials and configuration to be passed in as options instead of the connection url. This PR parses the url and puts it in a keyword list.

Generate connection map from url

---

lib/railway_ipc/core/requests_consumer.ex
lib/railway_ipc/events_consumer.ex
lib/railway_ipc/ipc/consumers/republished_messages_consumer.ex
lib/railway_ipc/ipc/publishers/republished_messages_publisher.ex
lib/railway_ipc/message_consumption.ex
lib/railway_ipc/message_consumption_behaviour.ex
lib/railway_ipc/message_publishing.ex
lib/railway_ipc/persistence.ex
lib/railway_ipc/requests_consumer.ex
test/railway_ipc/commands_consumer_test.exs
test/railway_ipc/consumed_message_test.exs
test/railway_ipc/core/requests_consumer_test.exs
test/railway_ipc/events_consumer_test.exs
test/railway_ipc/ipc/publishers/republished_messages_pubisher_test.exs
test/railway_ipc/message_consumption_test.exs
test/railway_ipc/message_publishing_test.exs
test/railway_ipc/persistence/published_message_adapter_test.exs
test/railway_ipc/persistence_test.exs
test/railway_ipc/published_message_test.exs
test/railway_ipc/publisher_test.exs
test/railway_ipc/railway_ipc_test.exs
test/railway_ipc/requests_consumer_test.exs
test/support/factory.ex

Credo expects aliases to be in alphabetical order.

Fix Credo warnings

---

test/railway_ipc/ipc/consumers/republished_messages_consumer_test.exs
test/railway_ipc/ipc/publishers/republished_messages_pubisher_test.exs
test/railway_ipc/publisher_test.exs
test/railway_ipc/republish_command_consumer_test.exs
test/railway_ipc/utils_test.exs
test/support/data_case.ex

Have Credo ignore AliasUsage warnings (mostly in tests)

Ignore AliasUsage in tests

---

bin/ci
config/e2e.exs
lib/railway_ipc/application.ex
mix.exs
test/e2e/consumer_test.exs
test/e2e/publisher_test.exs
test/support/data_case.ex
test/support/helpers.ex
test/support/rabbit_case.ex
test/test_helper.exs

All this mocking without at least a couple of end to end "happy path" tests makes be nervous. This sets up the infrastructure necessary to do end to end testing. It's a little complicated due to how Mox works (eventually, I'd like to get rid of Mox) because we have to use a separate `MIX_ENV`. Since e2e tests will be slower than the mocked tests, we'll run them separately using tags. They also won't be run by the default `mix test` task. You can run them explicitly using the command `MIX_ENV=e2e mix test --only e2e`. CircleCI will run the e2e tests as a last step.
Right now there are two end to end tests, one for publishing a message and another for consuming a message.
This also includes some test helpers for dealing with RabbitMQ, Ecto and a better mechanism for waiting for something to …

End to end / smoke tests

---

lib/railway_ipc/core/events_consumer.ex
lib/railway_ipc/message_consumption.ex
lib/railway_ipc/message_consumption_behaviour.ex
test/railway_ipc/core/events_consumer_test.exs
test/railway_ipc/events_consumer_test.exs
test/railway_ipc/message_consumption_test.exs

Since we now only support "event" messages for the time being, there's no need to pass around the `EventMessage` module anymore. This simplifies function arguments, making future refactoring easier.

Refactor: No need to pass message module anymore

---

lib/railway_ipc/core/event_message.ex
lib/railway_ipc/core/events_consumer.ex
lib/railway_ipc/core/payload.ex
lib/railway_ipc/events_consumer.ex
lib/railway_ipc/message_consumption.ex
lib/railway_ipc/message_consumption_behaviour.ex
test/e2e/consumer_test.exs
test/railway_ipc/core/events_consumer_test.exs
test/railway_ipc/events_consumer_test.exs
test/support/rabbit_case.ex

Consumers now check the message metadata for a message format type which is used to decode the message. If one cannot be found, it falls back to assuming the message is a Base64 encoded binary protobuf. This allows us to support JSON protobufs without breaking existing message contracts.
This is a bit ugly due to both the way we mock things and the need to pass the message format down through several layers of functions.  Planning on getting rid of the unnecessary mocks and redundant layers in a separate PR.

Support for handing JSON protobufs

---

lib/railway_ipc/core/message_format/json_protobuf.ex
test/railway_ipc/core/message_format/binary_protobuf_test.exs
test/railway_ipc/core/message_format/json_protobuf_test.exs

Our Protobuf definitions define the context key like this:
```
map<string, string> context = <number>;
```
This presents an issue when decoding JSON protobufs, since the message is essentially a map with atom keys. When we decode a JSON protobuf we get back something like this:
```
%{
context: %{cohort_uuid: "9583f9c2-b484-44c7-8d6a-91ec3a1e85e9"},
correlation_id: "97ca5e16-bbf6-4fd8-9541-3a4f54b12f7e",
data: %LearnIpc.Events.BatchCreated.Data{
batch_iteration: "ONL02-SENG-FT-081820",
batch_url: "https://ironboard.lrn.sh/batches/2239",
batch_uuid: "6fe97e59-8478-4d32-a176-5d3aaab09091",
organization_uuid: "f0a7aae1-9fab-4a96-a0f7-00517feadd43"
},
user_uuid: "3ffd52f5-0339-4bcf-9e8f-51025bf8990d",
uuid: "611158a2-5c5b-4687-ad53-bd9a3be4e235"
}
```
Notice the context key "cohort_uuid" is an …

Protobuf message context maps have string keys

---

CHANGELOG.md
lib/railway_ipc/core/payload.ex
lib/railway_ipc/core/published_message.ex
lib/railway_ipc/message_publihsing_behaviour.ex
lib/railway_ipc/message_publishing.ex
lib/railway_ipc/publisher.ex
lib/railway_ipc/rabbit_mq/rabbit_mq_adapter.ex
lib/railway_ipc/stream_behaviour.ex
test/e2e/publisher_test.exs
test/railway_ipc/core/message_format/binary_protobuf_test.exs
test/railway_ipc/core/payload_test.exs
test/railway_ipc/message_publishing_test.exs
test/railway_ipc/persistence/published_message_adapter_test.exs
test/railway_ipc/persistence_test.exs
test/railway_ipc/published_message_test.exs
test/railway_ipc/publisher_test.exs
test/railway_ipc/rabbit_mq/rabbit_mq_adapter_test.exs

Support for publishing messages in JSON protobuf format. The `#publish` macro now takes an optional second argument which indicates the message format to use. The value can be either `"json_protobuf"` or `"binary_protobuf"`. If the argument is omitted, `"binary_protobuf"` is used. The message format argument is then passed down through the call chain to the `Payload` module.
There were some redundant tests between `Payload` and `MessageFormat.BinaryProtobuf` that were removed from the `Payload` test module. Added new tests for the `Payload` module to cover the various formats. Updated remaining tests to pass the message format through the call chain.

JSON protobuf encoding

---

lib/railway_ipc/core/payload.ex
lib/railway_ipc/publisher.ex
test/railway_ipc/core/payload_test.exs
test/railway_ipc/publisher_test.exs

Move the UUID check down into the `Payload#encode` function. Remove direct `ensure_uuid` usages in `Publisher`. Add a test for `Payload#encode` that checks a UUID is generated if one isn't provided.  Note that we don't need to add a test to ensure a given UUID is not overridden since it's covered by other tests. Remove redundant UUID tests from the `Publisher` test file.

Refactor `ensure_uuid`

---

CHANGELOG.md
lib/railway_ipc/application.ex
lib/railway_ipc/loggers/publisher_events.ex
lib/railway_ipc/publisher.ex
lib/telemetry.ex

Remove RPC publishing support and related logging, telemetry, etc. Looks like this feature wasn't tested, so there's no tests to delete.
Closes #55

Remove publisher RPC support

---

lib/railway_ipc/core/message_format/json_protobuf.ex
test/railway_ipc/core/message_format/json_protobuf_test.exs
test/support/ipc/messages/admitted_applicant.pb.ex
test/support/ipc/messages/applicant_admitted.pb.ex

I didn't realize we allow arbitrarily nested protobufs. Recursively ensure that each part of a given protobuf struct is converted to a map. Prevents JSON encoder `Protocol.UndefinedError`'s.

Fix encoding of arbitrarily nested protobufs

---

lib/railway_ipc/message_bus.ex
lib/railway_ipc/message_bus/rabbitmq/adapter.ex
lib/railway_ipc/message_bus/rabbitmq/logger.ex
lib/railway_ipc/message_bus/rabbitmq/telemetry.ex
lib/telemetry.ex
test/railway_ipc/message_bus/rabbitmq/adapter_test.exs

Lay the groundwork to eventually replace the overly broad interface of `StreamBehaviour` and its related modules. This is all "dark code", nothing is using this new `MessageBus` yet. Rather than making one giant refactoring commit I'm breaking this up into smaller chunks to make reviewing easier.

Introduce `MessageBus` abstraction

---

test/support/helpers.ex

Small macro helper for tests. Useful for ensuring a side effect occurred. See the docstring for an example.

`assert_difference` macro for tests

---

lib/railway_ipc/storage.ex
lib/railway_ipc/storage/db/adapter.ex
lib/railway_ipc/storage/db/errors.ex
lib/railway_ipc/storage/db/published_message.ex
test/railway_ipc/storage/db/adapter_test.exs
test/railway_ipc/storage/db/published_message_test.exs
test/support/data_case.ex

Rather than trying to refactor persistence code that contains some circular dependencies, add a parallel abstraction named `Storage`. This will eventually replace the existing persistence code. Currently, storage only deals with published messages, since I'm concentrating on the publisher half of the code.
This also refactors `DataCase` a bit, removing some unused code and cleaning up the setup code.
All of this is "dark code", nothing is using it yet.

Storage abstraction
